name: "create branch and release"

on:
  workflow_dispatch:
    inputs:
      submodule:
        description: "The stage to publish to, ie. 'builds', 'releases'"
        required: true
      branch:
        description: "The component to publish, ie 'temporal', 'canary' etc."
        required: true

jobs:
  sync:
    name: "Update submodules"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Update Git Sumbodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
          git remote set-url origin https://x-access-token:${{ secrets.COMMANDER_DATA_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Update submodules" && git push || echo "No changes to commit"
