name: "Update submodule"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "submodule"
        required: true
      branch:
        description: "branch"
        required: true

jobs:
  sync:
    name: "Update submodules"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update Submodule branch
        env:
          SUBMODULE: ${{ github.event.inputs.repo }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          git switch $BRANCH || git switch -c $BRANCH
          git config --file=.gitmodules submodule.$SUBMODULE.branch $BRANCH
          git submodule update --init --recursive --remote

      - name: Commit update
        env:
          SUBMODULE: ${{ github.event.inputs.repo }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          git config --local user.name 'feedmeapples'
          git config --local user.email 'aksenov.ro@outlook.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Update submodule $SUBMODULE for branch $BRANCH"
          git push --set-upstream origin $BRANCH || echo "No changes to commit"
